# Generated by Django 3.0.5 on 2020-09-11 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('passenger', '0001_initial'),
        ('driver', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverrideshistory',
            name='passenger_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='passenger.Passenger'),
        ),
        migrations.AddField(
            model_name='driverlocation',
            name='driver_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='driver.Driver'),
        ),
    ]
